export const SORT_FIELDS_TEMPLATES = [
  {
    title: 'Recommended',
    value: 'recommended',
    isDefault: true,
  },
  {
    title: 'Name',
    value: 'name',
    isDefault: false,
  },
];

export const TEMPLATE_REQUEST_FORM =
  'https://forms.clickup.com/8591381/f/8660n-19378/MMG0TYTPJZAL32MZXC';

/**
 * Recommended order mapping based on weighted scores from analytics data
 * Lower numbers indicate higher priority (will appear first)
 */
export const RECOMMENDED_TEMPLATE_ORDER: Record<string, number> = {
  'linkedin-post-generator-m7ltws9o6z': 1,
  'lead-enrichment-agent-m7md03n6g4a': 2,
  'competitor-researcher-and-analyzer-m7t0ab0h49g': 3,
  'academic-quiz-master-m8cvyskbuqs': 4,
  'youtube-to-seo-content-maker-lxk52qawtmm': 5,
  'content-extractor-url-to-text': 6,
  'document-summarizer-lxx4fegp1b': 7,
  'seo-blog-post-writer-m7mi0bksagu': 8,
  'github-content-manager-ltghaklwrs': 9,
  'content-strategy-generator-luszv3obqx': 10,
  'email-outreach-writer-m7ng6dj21g': 11,
  'amazon-product-review-writer-m17vyjiw43g': 12,
  'knowledge-base-search-with-genai-m0v85uyy4n': 13,
  'blog-to-social-converter-m7ojhswtglp': 14,
  'business-expense-analyzer-m8x189zd53u': 15,
  'financial-statement-analyzer-m8wz9u9sls': 16,
  'hubspot-contacts-creator-ltf6vxjevaq': 17,
  'email-sender-lu2lt72m98k': 18,
  'tutorial__brand_agent': 19,
  'case-law-statute-researcher-m8hararxu9': 20,
  'product-recommendation-agent-lxx90ja8zki': 21,
  'founder-research-agent-m82y1ovmv5c': 22,
  'invoice-classifier-agent-m92jjh6n6k': 23,
  'bidirectional-messaging-agent-lvy9xokeesu': 24,
  'linkedin-leads-builder-lwexzixchw': 25,
  'azure-ai-vision-ocr-ltgkv9ncjh': 26,
  'resume-improvement-assistant-m91akqus6nu': 27,
  'meeting-preparation-agent-m91dusawyam': 28,
  'model-comparison-agent-m86hadsis8b': 29,
  'midjourney-agent-lv443mu22rd': 30,
  'news_research_agent': 31,
  'jira-service-desk-agent-m0fkbsvsec': 32,
  'content-summarizer-reviewer-m86cs7g39wa': 33,
  'invoice-processing-assistant-m87p24qq4e': 34,
  'kwrds-ai-seo-content-outliner-m73snf4n71r': 35,
  'transcript-analyzer-lx581qpwcq': 36,
  'tutorial__meme_maker': 37,
  'essay-writer-m87d3gfrpyd': 38,
  'file-analysis-agent-lxx540tx6a': 39,
  'seo-keyword-researcher-lxngosjnsxb': 40,
  'cover-letter-generator-m8x0w64icf': 41,
  'content_keyphrase_analyzer_agent': 42,
  'legal-document-review-agent-m8r8kqiylgd': 43,
  'backlink-analysis-agent-lxnw3jp8qz': 44,
  'mobile-message-sender-lu2mg4z5i4f': 45,
  'financial-news-podcaster-m87ly11j6rb': 46,
  'product-description-writer-with-vision': 47,
  'legal-document-creator-m88l4otwko7': 48,
  'smt_template__multimodal_thinking': 49,
  'transparent-bg-image-generator-ltqbf8r3j47': 50,
  'survey-response-analyzer-m8x076vajp': 51,
  'smt_basic_content_writer': 52,
  'blog-manager-Shopify': 53,
  'linkedin-news-roundup-maker-ly6730hdd4q': 54,
  'sentiment-and-emotion-analysis-agent': 55,
  'inflow_inventory_agent': 56,
  'essay-reviewer-m7t1xpx5utc': 57,
  'pdf-to-text-converter-ltq92c1ba38': 58,
  'lead-contacts-scraper': 59,
  'seo-keyword-researcher-ltgomx7lhn': 60,
  'job-interview-question-generator-m919qt551nt': 61,
  'press-release-agent-m0wisp23bi': 62,
  'estate-planner-agent-m87nhulxpf': 63,
  'customer-review-analysis-lxxqii7231': 64,
  'basic-folder-creator-dropbox': 65,
  'text-translator-with-audio-converter-ltrsknn0vxi': 66,
  'zendesk-leads-manager-ltinilztfg9': 67,
  'job-description-compliance-agent-m8x1p5x8ji': 68,
  'asana-tasks-manager-lx8ypir4kou': 69,
  'employee-onboarding-agent-lza2lnxbrlj': 70,
  'employee-onboarding-agent-m0v9951345': 71,
  'knowledge-checker-m7t57na7c3e': 72,
};
