const errKeys = {
  AGENT_LOCK_FAIL: 'AGENT_LOCK_FAIL',
  TEAM_OWNER_ONLY_ACTION: 'TEAM_OWNER_ONLY_ACTION',
  HAS_ACTIVE_SUBSCRIPTION: 'HAS_ACTIVE_SUBSCRIPTION',
  NOT_ENOUGH_PERMISSIONS: 'NOT_ENOUGH_PERMISSIONS',
  UNAUTHORIZED_ACTION: 'UNAUTHORIZED_ACTION',
  PAID_ONLY_FEATURE: 'PAID_ONLY_FEATURE',
  NOT_ALLOWED_TO_ACCESS_AGENT: 'NOT_ALLOWED_TO_ACCESS_AGENT',
};

export default errKeys;
